version: 2

build:
   os: "ubuntu-20.04"
   tools:
      python: "3.10"
   jobs:
      post_install:
         - pip install furo
      post_build:
         - cp build/html/_sources/*.txt rst/_build/html/_sources

sphinx:
   configuration: rst/conf.py
