version: 2

build:
   os: "ubuntu-20.04"
   tools:
      python: "3.10"
   commands:
      #
      # xrst
      - pip install xrst
      #
      # build/html
      - xrst
         --page_source
         --html_theme furo
         --group_list default
         --index_page_name cppad_py
      #
      # _readthedocs/html
      - mkdir _readthedocs
      - cp -r build/html _readthedocs/html
