version: 2

build:
   os: "ubuntu-20.04"
   tools:
      python: "3.10"
   commands:
      #
      # furo html theme
      - pip install furo pyspellchecker
      #
      # import spellchecker
      - pip install pyspellchecker
      #
      # xrst
      - pip install --index-url https://test.pypi.org/simple/ xrst
      #
      # build/html
      - xrst --page_source --html_theme furo
      #
      # _readthedocs/html
      - mkdir _readthedocs
      - cp -r build/html _readthedocs/html
