version: 2

build:
   os: "ubuntu-20.04"
   tools:
      python: "3.10"
   commands:
      #
      # xrst
      - pip install xrst
      #
      # This is only necessary if you need the most recent testing verison
      - pip uninstall -y xrst
      - pip install --index-url https://test.pypi.org/simple/ xrst
      #
      # This command prints the version of xrst that is being used
      - xrst --version
      #
      # build/html
      # This comamnd builds the xrst user documentaiton.
      # Suppress spell warnings because readthdocs uses a different dictionry.
      - xrst
         --page_source
         --html_theme sphinx_book_theme
         --group_list default user
         --index_page_name user-guide
         --suppress_spell_warnings
      #
      # _readthedocs/html
      # The directory that Read the Docs uploads when commands is used.
      - mkdir _readthedocs
      - rm -r build/html/.doctrees
      - cp -r build/html _readthedocs/html
