# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _cppad_swig
else:
    import _cppad_swig

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cppad_swig.delete_SwigPyIterator

    def value(self):
        return _cppad_swig.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _cppad_swig.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _cppad_swig.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _cppad_swig.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _cppad_swig.SwigPyIterator_equal(self, x)

    def copy(self):
        return _cppad_swig.SwigPyIterator_copy(self)

    def next(self):
        return _cppad_swig.SwigPyIterator_next(self)

    def __next__(self):
        return _cppad_swig.SwigPyIterator___next__(self)

    def previous(self):
        return _cppad_swig.SwigPyIterator_previous(self)

    def advance(self, n):
        return _cppad_swig.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _cppad_swig.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _cppad_swig.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _cppad_swig.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _cppad_swig.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _cppad_swig.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _cppad_swig.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _cppad_swig:
_cppad_swig.SwigPyIterator_swigregister(SwigPyIterator)

class a_double_data(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    value = property(_cppad_swig.a_double_data_value_get, _cppad_swig.a_double_data_value_set)
    tape_id = property(_cppad_swig.a_double_data_tape_id_get, _cppad_swig.a_double_data_tape_id_set)
    taddr = property(_cppad_swig.a_double_data_taddr_get, _cppad_swig.a_double_data_taddr_set)
    dynamic = property(_cppad_swig.a_double_data_dynamic_get, _cppad_swig.a_double_data_dynamic_set)

    def __init__(self):
        _cppad_swig.a_double_data_swiginit(self, _cppad_swig.new_a_double_data())
    __swig_destroy__ = _cppad_swig.delete_a_double_data

# Register a_double_data in _cppad_swig:
_cppad_swig.a_double_data_swigregister(a_double_data)

class a_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _cppad_swig.delete_a_double

    def __init__(self, *args):
        _cppad_swig.a_double_swiginit(self, _cppad_swig.new_a_double(*args))

    def value(self):
        return _cppad_swig.a_double_value(self)

    def parameter(self):
        return _cppad_swig.a_double_parameter(self)

    def variable(self):
        return _cppad_swig.a_double_variable(self)

    def near_equal(self, ae):
        return _cppad_swig.a_double_near_equal(self, ae)

    def var2par(self):
        return _cppad_swig.a_double_var2par(self)

    def __pos__(self):
        return _cppad_swig.a_double___pos__(self)

    def __neg__(self):
        return _cppad_swig.a_double___neg__(self)

    def __add__(self, *args):
        return _cppad_swig.a_double___add__(self, *args)

    def __sub__(self, *args):
        return _cppad_swig.a_double___sub__(self, *args)

    def __mul__(self, *args):
        return _cppad_swig.a_double___mul__(self, *args)

    def __truediv__(self, *args):
        return _cppad_swig.a_double___truediv__(self, *args)
    __div__ = __truediv__



    def __lt__(self, *args):
        return _cppad_swig.a_double___lt__(self, *args)

    def __le__(self, *args):
        return _cppad_swig.a_double___le__(self, *args)

    def __gt__(self, *args):
        return _cppad_swig.a_double___gt__(self, *args)

    def __ge__(self, *args):
        return _cppad_swig.a_double___ge__(self, *args)

    def __eq__(self, *args):
        return _cppad_swig.a_double___eq__(self, *args)

    def __ne__(self, *args):
        return _cppad_swig.a_double___ne__(self, *args)

    def __iadd__(self, *args):
        return _cppad_swig.a_double___iadd__(self, *args)

    def __isub__(self, *args):
        return _cppad_swig.a_double___isub__(self, *args)

    def __imul__(self, *args):
        return _cppad_swig.a_double___imul__(self, *args)

    def __itruediv__(self, *args):
        return _cppad_swig.a_double___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def abs(self):
        return _cppad_swig.a_double_abs(self)

    def acos(self):
        return _cppad_swig.a_double_acos(self)

    def asin(self):
        return _cppad_swig.a_double_asin(self)

    def atan(self):
        return _cppad_swig.a_double_atan(self)

    def cos(self):
        return _cppad_swig.a_double_cos(self)

    def cosh(self):
        return _cppad_swig.a_double_cosh(self)

    def erf(self):
        return _cppad_swig.a_double_erf(self)

    def exp(self):
        return _cppad_swig.a_double_exp(self)

    def fabs(self):
        return _cppad_swig.a_double_fabs(self)

    def log(self):
        return _cppad_swig.a_double_log(self)

    def sin(self):
        return _cppad_swig.a_double_sin(self)

    def sinh(self):
        return _cppad_swig.a_double_sinh(self)

    def sqrt(self):
        return _cppad_swig.a_double_sqrt(self)

    def tan(self):
        return _cppad_swig.a_double_tan(self)

    def tanh(self):
        return _cppad_swig.a_double_tanh(self)

    def cond_assign(self, cop, left, right, if_true, if_false):
        return _cppad_swig.a_double_cond_assign(self, cop, left, right, if_true, if_false)

    def __radd__(self, d):
        return _cppad_swig.a_double___radd__(self, d)

    def __rsub__(self, d):
        return _cppad_swig.a_double___rsub__(self, d)

    def __rmul__(self, d):
        return _cppad_swig.a_double___rmul__(self, d)

    def __rtruediv__(self, d):
        return _cppad_swig.a_double___rtruediv__(self, d)

    def __rpow__(self, d):
        return _cppad_swig.a_double___rpow__(self, d)

    def __pow__(self, *args):
        return _cppad_swig.a_double___pow__(self, *args)

# Register a_double in _cppad_swig:
_cppad_swig.a_double_swigregister(a_double)


def radd(d, ad):
    return _cppad_swig.radd(d, ad)

def rsub(d, ad):
    return _cppad_swig.rsub(d, ad)

def rmul(d, ad):
    return _cppad_swig.rmul(d, ad)

def rdiv(d, ad):
    return _cppad_swig.rdiv(d, ad)

def pow(*args):
    return _cppad_swig.pow(*args)
class sparse_rc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _cppad_swig.sparse_rc_swiginit(self, _cppad_swig.new_sparse_rc())
    __swig_destroy__ = _cppad_swig.delete_sparse_rc

    def resize(self, nr, nc, nnz):
        return _cppad_swig.sparse_rc_resize(self, nr, nc, nnz)

    def nr(self):
        return _cppad_swig.sparse_rc_nr(self)

    def nc(self):
        return _cppad_swig.sparse_rc_nc(self)

    def nnz(self):
        return _cppad_swig.sparse_rc_nnz(self)

    def put(self, k, r, c):
        return _cppad_swig.sparse_rc_put(self, k, r, c)

    def row(self):
        return _cppad_swig.sparse_rc_row(self)

    def col(self):
        return _cppad_swig.sparse_rc_col(self)

    def row_major(self):
        return _cppad_swig.sparse_rc_row_major(self)

    def col_major(self):
        return _cppad_swig.sparse_rc_col_major(self)

# Register sparse_rc in _cppad_swig:
_cppad_swig.sparse_rc_swigregister(sparse_rc)

class sparse_rcv(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, pattern):
        _cppad_swig.sparse_rcv_swiginit(self, _cppad_swig.new_sparse_rcv(pattern))
    __swig_destroy__ = _cppad_swig.delete_sparse_rcv

    def put(self, k, v):
        return _cppad_swig.sparse_rcv_put(self, k, v)

    def nr(self):
        return _cppad_swig.sparse_rcv_nr(self)

    def nc(self):
        return _cppad_swig.sparse_rcv_nc(self)

    def nnz(self):
        return _cppad_swig.sparse_rcv_nnz(self)

    def row(self):
        return _cppad_swig.sparse_rcv_row(self)

    def col(self):
        return _cppad_swig.sparse_rcv_col(self)

    def val(self):
        return _cppad_swig.sparse_rcv_val(self)

    def row_major(self):
        return _cppad_swig.sparse_rcv_row_major(self)

    def col_major(self):
        return _cppad_swig.sparse_rcv_col_major(self)

# Register sparse_rcv in _cppad_swig:
_cppad_swig.sparse_rcv_swigregister(sparse_rcv)

class sparse_jac_work(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _cppad_swig.sparse_jac_work_swiginit(self, _cppad_swig.new_sparse_jac_work())
    __swig_destroy__ = _cppad_swig.delete_sparse_jac_work

    def clear(self):
        return _cppad_swig.sparse_jac_work_clear(self)

# Register sparse_jac_work in _cppad_swig:
_cppad_swig.sparse_jac_work_swigregister(sparse_jac_work)

class sparse_hes_work(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _cppad_swig.sparse_hes_work_swiginit(self, _cppad_swig.new_sparse_hes_work())
    __swig_destroy__ = _cppad_swig.delete_sparse_hes_work

    def clear(self):
        return _cppad_swig.sparse_hes_work_clear(self)

# Register sparse_hes_work in _cppad_swig:
_cppad_swig.sparse_hes_work_swigregister(sparse_hes_work)


def independent(*args):
    return _cppad_swig.independent(*args)

def abort_recording():
    return _cppad_swig.abort_recording()
class d_fun(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, ax, ay):
        _cppad_swig.d_fun_swiginit(self, _cppad_swig.new_d_fun(ax, ay))

    def size_domain(self):
        return _cppad_swig.d_fun_size_domain(self)

    def size_range(self):
        return _cppad_swig.d_fun_size_range(self)

    def size_var(self):
        return _cppad_swig.d_fun_size_var(self)

    def size_op(self):
        return _cppad_swig.d_fun_size_op(self)

    def size_order(self):
        return _cppad_swig.d_fun_size_order(self)

    def new_dynamic(self, dynamic):
        return _cppad_swig.d_fun_new_dynamic(self, dynamic)

    def forward(self, p, xp):
        return _cppad_swig.d_fun_forward(self, p, xp)

    def reverse(self, q, yq):
        return _cppad_swig.d_fun_reverse(self, q, yq)

    def jacobian(self, x):
        return _cppad_swig.d_fun_jacobian(self, x)

    def hessian(self, x, w):
        return _cppad_swig.d_fun_hessian(self, x, w)

    def optimize(self):
        return _cppad_swig.d_fun_optimize(self)

    def to_json(self):
        return _cppad_swig.d_fun_to_json(self)

    def from_json(self, json):
        return _cppad_swig.d_fun_from_json(self, json)

    def for_jac_sparsity(self, pattern_in, pattern_out):
        return _cppad_swig.d_fun_for_jac_sparsity(self, pattern_in, pattern_out)

    def rev_jac_sparsity(self, pattern_in, pattern_out):
        return _cppad_swig.d_fun_rev_jac_sparsity(self, pattern_in, pattern_out)

    def for_hes_sparsity(self, select_domain, select_range, pattern_out):
        return _cppad_swig.d_fun_for_hes_sparsity(self, select_domain, select_range, pattern_out)

    def rev_hes_sparsity(self, select_domain, select_range, pattern_out):
        return _cppad_swig.d_fun_rev_hes_sparsity(self, select_domain, select_range, pattern_out)

    def sparse_jac_for(self, subset, x, pattern, work):
        return _cppad_swig.d_fun_sparse_jac_for(self, subset, x, pattern, work)

    def sparse_jac_rev(self, subset, x, pattern, work):
        return _cppad_swig.d_fun_sparse_jac_rev(self, subset, x, pattern, work)

    def sparse_hes(self, subset, x, r, pattern, work):
        return _cppad_swig.d_fun_sparse_hes(self, subset, x, r, pattern, work)
    __swig_destroy__ = _cppad_swig.delete_d_fun

# Register d_fun in _cppad_swig:
_cppad_swig.d_fun_swigregister(d_fun)

class a_fun(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, g):
        _cppad_swig.a_fun_swiginit(self, _cppad_swig.new_a_fun(g))
    __swig_destroy__ = _cppad_swig.delete_a_fun

    def size_domain(self):
        return _cppad_swig.a_fun_size_domain(self)

    def size_range(self):
        return _cppad_swig.a_fun_size_range(self)

    def size_var(self):
        return _cppad_swig.a_fun_size_var(self)

    def size_op(self):
        return _cppad_swig.a_fun_size_op(self)

    def size_order(self):
        return _cppad_swig.a_fun_size_order(self)

    def new_dynamic(self, adynamic):
        return _cppad_swig.a_fun_new_dynamic(self, adynamic)

    def forward(self, p, axp):
        return _cppad_swig.a_fun_forward(self, p, axp)

    def reverse(self, q, ayq):
        return _cppad_swig.a_fun_reverse(self, q, ayq)

    def jacobian(self, ax):
        return _cppad_swig.a_fun_jacobian(self, ax)

    def hessian(self, ax, aw):
        return _cppad_swig.a_fun_hessian(self, ax, aw)

# Register a_fun in _cppad_swig:
_cppad_swig.a_fun_swigregister(a_fun)

class fixed_solution(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    fixed_opt = property(_cppad_swig.fixed_solution_fixed_opt_get, _cppad_swig.fixed_solution_fixed_opt_set)
    fixed_lag = property(_cppad_swig.fixed_solution_fixed_lag_get, _cppad_swig.fixed_solution_fixed_lag_set)
    fix_con_lag = property(_cppad_swig.fixed_solution_fix_con_lag_get, _cppad_swig.fixed_solution_fix_con_lag_set)
    ran_con_lag = property(_cppad_swig.fixed_solution_ran_con_lag_get, _cppad_swig.fixed_solution_ran_con_lag_set)

    def __init__(self):
        _cppad_swig.fixed_solution_swiginit(self, _cppad_swig.new_fixed_solution())
    __swig_destroy__ = _cppad_swig.delete_fixed_solution

# Register fixed_solution in _cppad_swig:
_cppad_swig.fixed_solution_swigregister(fixed_solution)

class mixed(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, fixed_init, random_init, quasi_fixed, bool_sparsity, A_rcv, warning, fix_likelihood, fix_constraint, ran_likelihood):
        _cppad_swig.mixed_swiginit(self, _cppad_swig.new_mixed(fixed_init, random_init, quasi_fixed, bool_sparsity, A_rcv, warning, fix_likelihood, fix_constraint, ran_likelihood))
    __swig_destroy__ = _cppad_swig.delete_mixed

    def post_warning(self, message):
        return _cppad_swig.mixed_post_warning(self, message)

    def post_fatal_error(self, message):
        return _cppad_swig.mixed_post_fatal_error(self, message)

    def optimize_fixed(self, fixed_ipopt_options, random_ipopt_options, fixed_lower, fixed_upper, fix_constraint_lower, fix_constraint_upper, fixed_scale, fixed_in, random_lower, random_upper, random_in):
        return _cppad_swig.mixed_optimize_fixed(self, fixed_ipopt_options, random_ipopt_options, fixed_lower, fixed_upper, fix_constraint_lower, fix_constraint_upper, fixed_scale, fixed_in, random_lower, random_upper, random_in)

# Register mixed in _cppad_swig:
_cppad_swig.mixed_swigregister(mixed)

class vec_bool(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cppad_swig.vec_bool_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cppad_swig.vec_bool___nonzero__(self)

    def __bool__(self):
        return _cppad_swig.vec_bool___bool__(self)

    def __len__(self):
        return _cppad_swig.vec_bool___len__(self)

    def __getslice__(self, i, j):
        return _cppad_swig.vec_bool___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cppad_swig.vec_bool___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cppad_swig.vec_bool___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cppad_swig.vec_bool___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cppad_swig.vec_bool___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cppad_swig.vec_bool___setitem__(self, *args)

    def pop(self):
        return _cppad_swig.vec_bool_pop(self)

    def append(self, x):
        return _cppad_swig.vec_bool_append(self, x)

    def empty(self):
        return _cppad_swig.vec_bool_empty(self)

    def size(self):
        return _cppad_swig.vec_bool_size(self)

    def swap(self, v):
        return _cppad_swig.vec_bool_swap(self, v)

    def begin(self):
        return _cppad_swig.vec_bool_begin(self)

    def end(self):
        return _cppad_swig.vec_bool_end(self)

    def rbegin(self):
        return _cppad_swig.vec_bool_rbegin(self)

    def rend(self):
        return _cppad_swig.vec_bool_rend(self)

    def clear(self):
        return _cppad_swig.vec_bool_clear(self)

    def get_allocator(self):
        return _cppad_swig.vec_bool_get_allocator(self)

    def pop_back(self):
        return _cppad_swig.vec_bool_pop_back(self)

    def erase(self, *args):
        return _cppad_swig.vec_bool_erase(self, *args)

    def __init__(self, *args):
        _cppad_swig.vec_bool_swiginit(self, _cppad_swig.new_vec_bool(*args))

    def push_back(self, x):
        return _cppad_swig.vec_bool_push_back(self, x)

    def front(self):
        return _cppad_swig.vec_bool_front(self)

    def back(self):
        return _cppad_swig.vec_bool_back(self)

    def assign(self, n, x):
        return _cppad_swig.vec_bool_assign(self, n, x)

    def resize(self, *args):
        return _cppad_swig.vec_bool_resize(self, *args)

    def insert(self, *args):
        return _cppad_swig.vec_bool_insert(self, *args)

    def reserve(self, n):
        return _cppad_swig.vec_bool_reserve(self, n)

    def capacity(self):
        return _cppad_swig.vec_bool_capacity(self)
    __swig_destroy__ = _cppad_swig.delete_vec_bool

# Register vec_bool in _cppad_swig:
_cppad_swig.vec_bool_swigregister(vec_bool)

class vec_int(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cppad_swig.vec_int_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cppad_swig.vec_int___nonzero__(self)

    def __bool__(self):
        return _cppad_swig.vec_int___bool__(self)

    def __len__(self):
        return _cppad_swig.vec_int___len__(self)

    def __getslice__(self, i, j):
        return _cppad_swig.vec_int___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cppad_swig.vec_int___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cppad_swig.vec_int___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cppad_swig.vec_int___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cppad_swig.vec_int___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cppad_swig.vec_int___setitem__(self, *args)

    def pop(self):
        return _cppad_swig.vec_int_pop(self)

    def append(self, x):
        return _cppad_swig.vec_int_append(self, x)

    def empty(self):
        return _cppad_swig.vec_int_empty(self)

    def size(self):
        return _cppad_swig.vec_int_size(self)

    def swap(self, v):
        return _cppad_swig.vec_int_swap(self, v)

    def begin(self):
        return _cppad_swig.vec_int_begin(self)

    def end(self):
        return _cppad_swig.vec_int_end(self)

    def rbegin(self):
        return _cppad_swig.vec_int_rbegin(self)

    def rend(self):
        return _cppad_swig.vec_int_rend(self)

    def clear(self):
        return _cppad_swig.vec_int_clear(self)

    def get_allocator(self):
        return _cppad_swig.vec_int_get_allocator(self)

    def pop_back(self):
        return _cppad_swig.vec_int_pop_back(self)

    def erase(self, *args):
        return _cppad_swig.vec_int_erase(self, *args)

    def __init__(self, *args):
        _cppad_swig.vec_int_swiginit(self, _cppad_swig.new_vec_int(*args))

    def push_back(self, x):
        return _cppad_swig.vec_int_push_back(self, x)

    def front(self):
        return _cppad_swig.vec_int_front(self)

    def back(self):
        return _cppad_swig.vec_int_back(self)

    def assign(self, n, x):
        return _cppad_swig.vec_int_assign(self, n, x)

    def resize(self, *args):
        return _cppad_swig.vec_int_resize(self, *args)

    def insert(self, *args):
        return _cppad_swig.vec_int_insert(self, *args)

    def reserve(self, n):
        return _cppad_swig.vec_int_reserve(self, n)

    def capacity(self):
        return _cppad_swig.vec_int_capacity(self)
    __swig_destroy__ = _cppad_swig.delete_vec_int

# Register vec_int in _cppad_swig:
_cppad_swig.vec_int_swigregister(vec_int)

class vec_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cppad_swig.vec_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cppad_swig.vec_double___nonzero__(self)

    def __bool__(self):
        return _cppad_swig.vec_double___bool__(self)

    def __len__(self):
        return _cppad_swig.vec_double___len__(self)

    def __getslice__(self, i, j):
        return _cppad_swig.vec_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cppad_swig.vec_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cppad_swig.vec_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cppad_swig.vec_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cppad_swig.vec_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cppad_swig.vec_double___setitem__(self, *args)

    def pop(self):
        return _cppad_swig.vec_double_pop(self)

    def append(self, x):
        return _cppad_swig.vec_double_append(self, x)

    def empty(self):
        return _cppad_swig.vec_double_empty(self)

    def size(self):
        return _cppad_swig.vec_double_size(self)

    def swap(self, v):
        return _cppad_swig.vec_double_swap(self, v)

    def begin(self):
        return _cppad_swig.vec_double_begin(self)

    def end(self):
        return _cppad_swig.vec_double_end(self)

    def rbegin(self):
        return _cppad_swig.vec_double_rbegin(self)

    def rend(self):
        return _cppad_swig.vec_double_rend(self)

    def clear(self):
        return _cppad_swig.vec_double_clear(self)

    def get_allocator(self):
        return _cppad_swig.vec_double_get_allocator(self)

    def pop_back(self):
        return _cppad_swig.vec_double_pop_back(self)

    def erase(self, *args):
        return _cppad_swig.vec_double_erase(self, *args)

    def __init__(self, *args):
        _cppad_swig.vec_double_swiginit(self, _cppad_swig.new_vec_double(*args))

    def push_back(self, x):
        return _cppad_swig.vec_double_push_back(self, x)

    def front(self):
        return _cppad_swig.vec_double_front(self)

    def back(self):
        return _cppad_swig.vec_double_back(self)

    def assign(self, n, x):
        return _cppad_swig.vec_double_assign(self, n, x)

    def resize(self, *args):
        return _cppad_swig.vec_double_resize(self, *args)

    def insert(self, *args):
        return _cppad_swig.vec_double_insert(self, *args)

    def reserve(self, n):
        return _cppad_swig.vec_double_reserve(self, n)

    def capacity(self):
        return _cppad_swig.vec_double_capacity(self)
    __swig_destroy__ = _cppad_swig.delete_vec_double

# Register vec_double in _cppad_swig:
_cppad_swig.vec_double_swigregister(vec_double)

class vec_a_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cppad_swig.vec_a_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cppad_swig.vec_a_double___nonzero__(self)

    def __bool__(self):
        return _cppad_swig.vec_a_double___bool__(self)

    def __len__(self):
        return _cppad_swig.vec_a_double___len__(self)

    def __getslice__(self, i, j):
        return _cppad_swig.vec_a_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cppad_swig.vec_a_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cppad_swig.vec_a_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cppad_swig.vec_a_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cppad_swig.vec_a_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cppad_swig.vec_a_double___setitem__(self, *args)

    def pop(self):
        return _cppad_swig.vec_a_double_pop(self)

    def append(self, x):
        return _cppad_swig.vec_a_double_append(self, x)

    def empty(self):
        return _cppad_swig.vec_a_double_empty(self)

    def size(self):
        return _cppad_swig.vec_a_double_size(self)

    def swap(self, v):
        return _cppad_swig.vec_a_double_swap(self, v)

    def begin(self):
        return _cppad_swig.vec_a_double_begin(self)

    def end(self):
        return _cppad_swig.vec_a_double_end(self)

    def rbegin(self):
        return _cppad_swig.vec_a_double_rbegin(self)

    def rend(self):
        return _cppad_swig.vec_a_double_rend(self)

    def clear(self):
        return _cppad_swig.vec_a_double_clear(self)

    def get_allocator(self):
        return _cppad_swig.vec_a_double_get_allocator(self)

    def pop_back(self):
        return _cppad_swig.vec_a_double_pop_back(self)

    def erase(self, *args):
        return _cppad_swig.vec_a_double_erase(self, *args)

    def __init__(self, *args):
        _cppad_swig.vec_a_double_swiginit(self, _cppad_swig.new_vec_a_double(*args))

    def push_back(self, x):
        return _cppad_swig.vec_a_double_push_back(self, x)

    def front(self):
        return _cppad_swig.vec_a_double_front(self)

    def back(self):
        return _cppad_swig.vec_a_double_back(self)

    def assign(self, n, x):
        return _cppad_swig.vec_a_double_assign(self, n, x)

    def resize(self, *args):
        return _cppad_swig.vec_a_double_resize(self, *args)

    def insert(self, *args):
        return _cppad_swig.vec_a_double_insert(self, *args)

    def reserve(self, n):
        return _cppad_swig.vec_a_double_reserve(self, n)

    def capacity(self):
        return _cppad_swig.vec_a_double_capacity(self)
    __swig_destroy__ = _cppad_swig.delete_vec_a_double

# Register vec_a_double in _cppad_swig:
_cppad_swig.vec_a_double_swigregister(vec_a_double)



