# This file was automatically generated by xrst
#
# Project information
project = 'doc'
author = ''
#
# General configuration
extensions = [
   'sphinx.ext.mathjax',
   'sphinx_rtd_theme',
]
exclude_patterns = [
   'test_out',
   'preamble.rst',
]
#
# Theme
html_theme = 'sphinx_rtd_theme'
#
if html_theme == 'sphinx_rtd_theme' :
   html_theme_options = {
      'navigation_depth' : -1   ,
      'titles_only'      : True ,
   }
if html_theme == 'sphinx_book_theme' :
   html_theme_options = {
      'show_toc_level' : 4
   }
# furo theme uses default options
#
# Latex used when sphinx builds  pdf
latex_elements = {
    'preamble' :
    r'\renewcommand{\thesection}{{\hspace{-1em}}} ' +
    r'\renewcommand{\thesubsection}{{\hspace{-1em}}} ' +
    r'\renewcommand{\thesubsubsection}{{\hspace{-1em}}}' +
    r'\newcommand{\B}[1]{ {\bf #1} }' +
    r'\newcommand{\R}[1]{ {\rm #1} }'
}
